### ISSUE TITLE
Is it possible to use vuetify components ?

### ISSUE THREAD

**Issue by suryacaprice** [codotype/codotype#102]
https://vuetifyjs.com/ 

This is one of the widely used UI frameworks can you just give me a pointer on how to customize the generator output. I will modify for the vuetify and raise a pull request for it  . I will also try to add input validations with regular expression conditions and we need to have a validation based on a stored data value which will make it a complete experience. I currently use a laravel code generator and it does all this as well as generates customized dashboard components with SQL query. I would like to use it as a reference and improve accordingly

We can also use graphql instead of rest

**Comment by suryacaprice** [comment]
@aeksco if you can PM me at suryakumaran 11 at gmail dot com i can work with you to get more integration . I like this project and will work to improve it over time

**Comment by aeksco** [comment]
@suryacaprice Thanks for reaching out! This repository is actually for the core Codotype framework, which includes the generator runtime, generator packges, cli tools, ui components, and various utility packages to make it easier to incorporate Codotype into other projects.

If you'd like to see a feature addition to the Vue.js generator, please open an issue in the [codotype-vuejs-simple-generator](https://github.com/codotype/codotype-vuejs-simple-generator) repository.

If you're interested in building a new generator that includes PHP, GraphQL API, and other languages and packages (which it sounds like you are!), please open an issue in our [feature-requests](https://github.com/codotype/feature-requests) repository - thanks!
