### ISSUE TITLE
delete Modal in Relationship section

### ISSUE THREAD

**Issue by NeverBehave** [codotype/codotype#41]
# Description

Modal is covered by the top bar

# Reproduce 

- Create a new model and create a relationship
- click delete

![image](https://user-images.githubusercontent.com/17120571/55032709-e20c3000-4fe7-11e9-87e3-04963d6fb1b6.png)

# Environment

|key|value|
|-|-|
Google Chrome | 72.0.3626.121 (offcial) (64 bit)
Version | da3787ba355f18db7db52abf75c42afb408d656f-refs/branch-heads/3626@{#883}
OS | Mac OS X
JavaScript | V8 7.2.502.28

**Comment by aeksco** [comment]
@NeverBehave Thanks for opening this! This has actually been resolved on the dev branch - hopefully I'll have a moment to deploy the latest version before the end of the week. I'll leave this issue open until I wrap up that deploy :)

**Comment by NeverBehave** [comment]
Cool, glad to know that XD
