### ISSUE TITLE
Update Bootstrap and BootstrapVue

### ISSUE THREAD

**Issue by aeksco** [codotype/codotype#73]
The `bootstrap` and `bootstrap-vue` packages need to be updated to the latest versions in the `package.json` files the `@codotype/ui` and `@codotype/cli-ui`  packages.

**Comment by reachrahul** [comment]
@aeksco, Can I work on this?

**Comment by aeksco** [comment]
@reachrahul Just saw this comment! We've actually migrated the codebase to use React + Typescript, so this issue isn't relevant anymore. If you're interested in contributing to the project in other ways please feel free to jump into our Gitter Room! We'll also have a public Discord server set up shortly :D
